services:
  - type: web
    name: telegram-forward-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python forward_bot.py
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
